version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run:
          name: 'Update NPM'
          command: sudo npm install -g npm@6.9.0
      - run:
          name: 'Install Yarn'
          command: sudo npm install -g yarn@1.15.2
      - run:
          name: 'Set caching variables'
          command: |
            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/develop?filter=successful&limit=1"
            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`
            echo $LAST_SUCCESSFUL_COMMIT > /tmp/last-successful-commit
            echo $CIRCLE_SHA1 > /tmp/current-commit
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ checksum "/tmp/last-successful-commit" }}
      - run:
          name: 'Install Dependencies'
          command: yarn install
      - run:
          name: 'Build Packages'
          command: yarn build
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "/tmp/current-commit" }}
          paths:
            - ~/repo/packages/app/node_modules
            - ~/repo/packages/contract-addresses/lib
            - ~/repo/packages/protocol/node_modules
            - ~/repo/packages/subgraph/node_modules
  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.15.3
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: 'Lint Packages'
          command: |
            yarn prettier:ci
            yarn lint
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.18.1
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: 'Test Packages'
          command: yarn test

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - lint:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages
